micronaut:
  application:
    name: micronaut-api
netty:
  default:
    allocator:
      max-order: 3
vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: demo
      user: postgres
      password: postgres
      maxSize: 10
jpa:
  default:
    entity-scan:
      packages:
        - 'dev.rockyj.micronautapi.entities'
    properties:
      hibernate:
        show-sql: false
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres
    reactive: true
