micronaut:
  application:
    name: micronaut-api
  http:
    services:
      weatherService:
        url: http://localhost:3001
netty:
  default:
    allocator:
      max-order: 3
vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: demo
      user: postgres
      password: postgres
      maxSize: 10
jpa:
  default:
    entity-scan:
      packages:
        - 'dev.rockyj.micronautapi.entities'
    properties:
      hibernate:
        show-sql: false
        hbm2ddl:
          auto: validate
        connection:
          db-type: postgres
          username: postgres
          password: postgres
          url: "postgresql://localhost:5432/demo"
    reactive: true
