CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS genre;

CREATE TABLE genre (
   id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
   name  VARCHAR(255) NOT NULL UNIQUE,

   CONSTRAINT "genre_pkey" PRIMARY KEY ("id")
);

insert into genre (name) values('crime');
insert into genre (name) values('romance');